N=40
x=seq(-2,2,length=N)
deg=3
X1=x
X2=x^2
X3=x^3
X=cbind(1,X1,X2,X3)
p=ncol(X)
library(MASS)
beta <- c(1.3965,1.9407,-0.1215,0.1535)
eps=rnorm(N,0,1)
Y=X%*%beta+eps
betaHat=ginv(t(X)%*%X)%*%t(X)%*%Y
cov=solve(t(X)%*%X)
var_y1=diag(X2%*%t(X2)*cov[3,3])
y1=betaHat[3]*X2
plot(X1,y1,pch=20,type='b')
lines(X1,y1-2*sqrt(var_y1),pch=20)
lines(X1,y1+2*sqrt(var_y1),pch=20)
yHat=X%*%betaHat
sigma2=(1/(N-p))*sum((Y-yHat)^2)
varY=diag(X%*%ginv(t(X)%*%X)%*%t(X))
yHat_min=yHat-2*sqrt(varY)
yHat_max=yHat+2*sqrt(varY)
plot(x,Y,type='p')
points(x,yHat,type='l',col='red')
points(x,yHat_min,type='l',col='green')
points(x,yHat_max,type='l',col='green')
